<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HqBrand', 'doctrine');

/**
 * BaseHqBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image
 * @property clob $description
 * @property integer $parent_id
 * @property boolean $is_active
 * @property string $lang
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getImage()       Returns the current record's "image" value
 * @method clob    getDescription() Returns the current record's "description" value
 * @method integer getParentId()    Returns the current record's "parent_id" value
 * @method boolean getIsActive()    Returns the current record's "is_active" value
 * @method string  getLang()        Returns the current record's "lang" value
 * @method HqBrand setName()        Sets the current record's "name" value
 * @method HqBrand setImage()       Sets the current record's "image" value
 * @method HqBrand setDescription() Sets the current record's "description" value
 * @method HqBrand setParentId()    Sets the current record's "parent_id" value
 * @method HqBrand setIsActive()    Sets the current record's "is_active" value
 * @method HqBrand setLang()        Sets the current record's "lang" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHqBrand extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hq_brand');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'ten nha phan phoi',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'anh dai dien',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             'comment' => 'Trạng thái',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}