<?php

/**
 * AdProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdProduct');
    }

    public static function getAllService($isActive, $limit)
    {
        $query = AdProductTable::getInstance()->createQuery()
            ->select()
            ->orderBy('category_id DESC')
            ->limit($limit);
        if ($isActive != 2) {
            $query->where('is_active=?', $isActive);
        }
        return $query->fetchArray();
    }

    public static function checkSlug($slug, $id)
    {
        $query = AdProductTable::getInstance()->createQuery()
            ->select('slug')
            ->where('slug=?', $slug)
            ->andWhere('id<>?', $id);
        return $query;
    }

    public static function getServiceBySlug($slug)
    {
        $query = AdProductTable::getInstance()->createQuery()
            ->where('slug=?', $slug);
        return $query->fetchOne();
    }
}