<?php

/**
 * HqBrandTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HqBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HqBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HqBrand');
    }

    public static function getAllBrand()
    {
        return HqBrandTable::getInstance()->createQuery()->execute();
    }

    public static function getBrandById($id)
    {
        return HqBrandTable::getInstance()->createQuery()
            ->andWhere('id=?', $id)
            ->fetchOne();
    }

    public static function getBrandBySlug($slug)
    {
        return HqBrandTable::getInstance()->createQuery()
            ->andWhere('slug=?', $slug)
            ->fetchOne();
    }

    public static function getBrandByParentID($parentId, $limit = null)
    {
        $query = HqBrandTable::getInstance()->createQuery()
            ->where(($parentId != '') ? 'parent_id=?' : '(parent_id=? or parent_id is null)', $parentId)
            ->andWhere('is_active=1')
            ->orderby('priority desc');
        if ($limit != null) {
            $query->limit($limit);
        }
        return $query->fetchArray();
    }
}