<?php

/**
 * HqBrandTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HqBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HqBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HqBrand');
    }

    public static function getAllBrand()
    {
        return HqBrandTable::getInstance()->createQuery()->execute();
    }

    public static function getBrandById($id)
    {
        return HqBrandTable::getInstance()->createQuery()
            ->andWhere('id=?', $id)
            ->fetchOne();
    }
}