# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
service:
  url: /service/:slug
  param: {module: pageIntroduction, action: service}
page_search:
  url:  /search
  param: { module: pageProduct, action: search}
policy:
  url: /policy
  param: {module: pageIntroduction, action: policy}
contact_us:
  url: /contact-us
  param: {module: pageIntroduction, action: contact}
#về chúng tôi
about_us:
  url: /about-us
  param: {module: pageIntroduction, action: index}
hq_product:
  url: /product/:slug/:page
  param: {module: pageProduct, action: index, page: 1, slug: ""}
hq_brand:
  url: /brand/:slug/:page
  param: {module: pageProduct, action: brand, page: 1, slug: ""}
hq_product_detail:
  url: /product-detail/:slug
  param: {module: pageProduct, action: detail, slug: ""}
ajax_inquiry_now:
  url: /inquiry-now
  param: {module: pageProduct, action: inquiryNow}
ajax_popup_inquiry_now:
  url: /popup-inquiry-now
  param: {module: pageProduct, action: popupInquiryNow}
pageInquiryNow:
  url: /inquiry-now/:slug
  param: {module: pageProduct, action: pageInquiryNow}
hq_news:
  url: /news/:page
  param: {module: pageNews, action: index, page: 1, slug: ""}
hq_news_search:
  url: /search-new
  param: {module: pageNews, action: searchNew}
hq_new_category:
  url: /category/:slug/:page
  param: {module: pageNews, action: listNews, page: 1, slug: ""}
hq_new_detail:
  url: /new-detail/:slug
  param: {module: pageNews, action: detail, slug: ""}


# default rules
homepage:
  url:   /:lang
#  param: { module: pageHome, action: index }
  param: { module: pageHome, action: index, lang: '' }
  requirements: { sf_method: get }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
